Wiz\ErrorLogBundle\Entity\ErrorType:
    type: entity
    table: wiz_error_type
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
                
    fields:
        type:
            type: string
            length: 50
