Wiz\ErrorLogBundle\Entity\Owner:
    type: entity
    table: wiz_owner
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
                
    fields:
        Name:
            type: string
            length: 250
        Mail:
            type: string
            length: 250
            
    manyToMany:
        Projects:
            targetEntity: Wiz\ErrorLogBundle\Entity\Project
            inversedBy: Owners
            joinTable:
                name: wiz_project_owner
                joinColumns:
                    ProjectId:
                        referencedColumnName: id
                inverseJoinColumns:
                    OwnerId:
                        referencedColumnName: id
